name: Deployment

on:
  push:
  pull_request:

jobs:
  compose-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Docker Compose config
        run: docker compose -f deploy/docker-compose.yaml config
